-- Mishkat League database schema
-- Neon project: misty-shadow-06396184 / branch: production

CREATE TABLE IF NOT EXISTS app_config (
  id smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  school_name text NOT NULL,
  app_name text NOT NULL,
  season text NOT NULL,
  rules jsonb NOT NULL DEFAULT '[]'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS leagues (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  points_win smallint NOT NULL DEFAULT 3,
  points_draw smallint NOT NULL DEFAULT 1,
  points_loss smallint NOT NULL DEFAULT 0,
  sort_order smallint NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS teams (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  league_id bigint NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  name text NOT NULL,
  short_name text,
  sort_order smallint NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (league_id, name)
);

CREATE TABLE IF NOT EXISTS matches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_no smallint NOT NULL UNIQUE,
  league_id bigint NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  round_no smallint NOT NULL DEFAULT 1,
  match_date date NOT NULL,
  day_name text NOT NULL,
  home_team_id bigint NOT NULL REFERENCES teams(id),
  away_team_id bigint NOT NULL REFERENCES teams(id),
  home_score smallint CHECK (home_score IS NULL OR home_score >= 0),
  away_score smallint CHECK (away_score IS NULL OR away_score >= 0),
  status text NOT NULL DEFAULT 'scheduled'
    CHECK (status IN ('scheduled','completed','postponed')),
  notes text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (home_team_id <> away_team_id)
);

CREATE TABLE IF NOT EXISTS audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action text NOT NULL,
  match_id bigint REFERENCES matches(id) ON DELETE SET NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_matches_league_date
  ON matches (league_id, match_date, match_no);

CREATE OR REPLACE VIEW league_standings AS
SELECT
  t.id AS team_id,
  t.league_id,
  t.name AS team_name,
  t.sort_order,
  COUNT(m.id) FILTER (WHERE m.status = 'completed')::int AS played,
  COUNT(m.id) FILTER (
    WHERE m.status = 'completed'
      AND ((m.home_team_id = t.id AND m.home_score > m.away_score)
        OR (m.away_team_id = t.id AND m.away_score > m.home_score))
  )::int AS won,
  COUNT(m.id) FILTER (
    WHERE m.status = 'completed' AND m.home_score = m.away_score
  )::int AS drawn,
  COUNT(m.id) FILTER (
    WHERE m.status = 'completed'
      AND ((m.home_team_id = t.id AND m.home_score < m.away_score)
        OR (m.away_team_id = t.id AND m.away_score < m.home_score))
  )::int AS lost,
  COALESCE(SUM(CASE
    WHEN m.status <> 'completed' THEN 0
    WHEN m.home_team_id = t.id THEN m.home_score
    ELSE m.away_score END),0)::int AS goals_for,
  COALESCE(SUM(CASE
    WHEN m.status <> 'completed' THEN 0
    WHEN m.home_team_id = t.id THEN m.away_score
    ELSE m.home_score END),0)::int AS goals_against,
  (
    COUNT(m.id) FILTER (
      WHERE m.status = 'completed'
        AND ((m.home_team_id = t.id AND m.home_score > m.away_score)
          OR (m.away_team_id = t.id AND m.away_score > m.home_score))
    ) * l.points_win
    + COUNT(m.id) FILTER (
      WHERE m.status = 'completed' AND m.home_score = m.away_score
    ) * l.points_draw
  )::int AS points
FROM teams t
JOIN leagues l ON l.id = t.league_id
LEFT JOIN matches m
  ON m.league_id = t.league_id
 AND (m.home_team_id = t.id OR m.away_team_id = t.id)
GROUP BY t.id, t.league_id, t.name, t.sort_order, l.points_win, l.points_draw;
